package org.artools.orbitcalculator.application.kepler;

public enum KeplerElement {
  // ELLIPTICAL ELEMENTS
  ECCENTRICITY,
  SEMI_MAJOR_AXIS,
  APOAPSIS,
  PERIAPSIS,
  // DERIVED ELLIPTICAL ELEMENTS
  ORBITAL_PERIOD, // DIRECTLY DERIVED FROM SMA
  // ROTATIONAL ELEMENTS
  INCLINATION,
  LONGITUDE_ASCENDING_NODE,
  ARGUMENT_OF_PERIAPSIS,
  // POSITION ELEMENTS
  MEAN_ANOMALY,
  ECCENTRIC_ANOMALY,
  TRUE_ANOMALY,
  // DERIVED POSITION ELEMENTS
  TIME_TO_PERIAPSIS // DIRECTLY DERIVED FROM MEAN ANOMALY
}
